---
title: "PM2.5 Corrections"
author: "Audrey Smith"
date: "4/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(lubridate)
library(stringr)
library(httr)
library(jsonlite)
```

EPA Air Quality System API Docs:
https://aqs.epa.gov/aqsweb/documents/data_api.html

### Set up Query and Determine Desired Parameters
```{r}
aqs_base_url <- 'https://aqs.epa.gov/data/api/'
aqs_user_key <- '?email=audrey@psehealthyenergy.org&key=taupewren34'

sac_fips <- '067'
t_st_code <- '0010'

cc_fips <- '013'
```

```{r}
get_aqs_data <- function(output_type, requested_data){
  
  request_url <- paste0(aqs_base_url, output_type, aqs_user_key, requested_data)
  
  aqs_data <- httr::GET(request_url) %>%
    content(as = 'text', type = NULL, encoding = 'UTF-8') %>%
    fromJSON() %>%
    data.frame() %>%
    select(starts_with('Data'))
  
  colnames(aqs_data) <- str_remove(colnames(aqs_data), 'Data.')
  
  return(aqs_data)
}
```

```{r}
list_params <- get_aqs_data('list/parametersByClass', '&pc=ALL')
t_st_sensors <- get_aqs_data('monitors/bySite', '&bdate=20150501&edate=20150502&state=06&county=067&site=0010')
```

### Query for Pollutants & Climate Metrics of Interest
```{r}
get_param_code <- function(metric_value){ 
  code <- list_params[list_params['value_represented'] == metric_value, 'code']
  return(code)
}
```

```{r}
get_multiyear_data <- function(metric_value){
  
  param_code <- get_param_code(metric_value)
  print(metric_value)
  print(param_code)
  data_19 <- get_aqs_data('sampleData/bySite', paste0('&param=', param_code, '&bdate=20190715&edate=20191231&state=06&county=067&site=0010'))
  data_20 <- get_aqs_data('sampleData/bySite', paste0('&param=', param_code, '&bdate=20200101&edate=20200229&state=06&county=067&site=0010'))
  
  data_multiyr <- rbind(data_19, data_20) %>%
    mutate(Time = paste0(date_local, ' ', time_local, ':00')) %>%
    filter(sample_frequency == 'HOURLY')
  
  parameter <- unique(data_multiyr$parameter)
  units <- unique(data_multiyr$units_of_measure)
  frequency <- unique(data_multiyr$sample_frequency)
  
  print(paste('Downloaded data for', parameter, units, 'at frequency', frequency))
  
  data_multiyr <- select(data_multiyr, Time, latitude, longitude, sample_measurement)
  
  return(data_multiyr)
}
```

```{r}
arrange(t_st_sensors[,c('parameter_name', 'parameter_code', 'open_date', 'close_date', 'naaqs_primary_monitor', 'local_site_name')], parameter_name)
```

```{r, warning = FALSE}
O3_sac <- get_multiyear_data('Ozone') %>% rename('O3_carb'='sample_measurement')
NO2_sac <- get_multiyear_data('Nitrogen dioxide (NO2)') %>% rename('NO2_carb'='sample_measurement')
PM25_sac <- get_multiyear_data('Acceptable PM2.5 AQI & Speciation Mass') %>% rename('PM25_carb'='sample_measurement')

TEMP_sac <- get_multiyear_data('Outdoor Temperature') %>% rename('TEMP_carb'='sample_measurement')
RH_sac <- get_multiyear_data('Relative Humidity ') %>% rename('RH_carb'='sample_measurement')
```

```{r, message = FALSE}
carb_data <- full_join(PM25_sac, TEMP_sac) %>%
  full_join(RH_sac)
```

### Read in PSE Data, Join Data
```{r}
aqy_data <- read.csv("data/sac_colocation_hourly_correctedRaw.csv") %>%
  select(Time, ID, PM25_raw, temp, RH, DP) %>%
  rename('PM25_pse'='PM25_raw', 'TEMP_pse'='temp', 'RH_pse'='RH', 'DP_pse'='DP')
```

```{r}
pse_carb_data <- aqy_data %>%
  mutate(TEMP_pse = (9/5)*TEMP_pse + 32) %>%
  inner_join(carb_data, by = 'Time') %>%
  mutate(time_dt = as_datetime(Time))
```

```{r}
grid_pm_carb_pse <- ggplot(data = pse_carb_data, aes(x = PM25_carb, y = PM25_pse)) +
  geom_point(size = .5) +
  facet_wrap(~ID) +
  theme(axis.text = element_text(size = 6),
        strip.text.x = element_text(size = 6), 
        strip.background.x = element_rect(fill = F))

grid_pm_carb_pse
grid_pm_carb_pse + ylim(c(0, 60))
```


### Define Functions for Linear Regression
```{r}
get_model_outputs <- function(linear_model, aqy_id = NULL){
  
  if(is.null(aqy_id)){aqy_id <- 'Network'}
    else{aqy_id <- aqy_id}
  
  lin_model_summary <-  summary(linear_model)
  
  f_stat <- lin_model_summary$fstatistic
  
  p_val <- round(pf(f_stat[1],f_stat[2],f_stat[3], lower.tail = F), 3)
  r2_adj <- round(lin_model_summary$adj.r.squared, 3)
  coeff_intercept <- round(linear_model$coefficients[1], 3)
  coeff_pmcarb <- round(linear_model$coefficients[2], 3)
  
  model_outputs <- data.frame(cbind(aqy_id, r2_adj, p_val, coeff_intercept, coeff_pmcarb))
  colnames(model_outputs) <- c('ID', 'r2_adj', 'p_val', 'coef_intercept', 'coef_pmcarb')
  
  return(model_outputs)
}
```

```{r}
run_lm_pse_carb_aqy <- function(aqy_id = NULL, response, predictor){
  
  if(is.null(aqy_id)){model_data = pse_carb_data
                      aqy_id <- 'Network'}
    else{model_data = subset(pse_carb_data, ID == aqy_id)}
  
  model_formula <- as.formula(paste(response, '~', predictor))
  lin_model <- lm(formula = model_formula, data = model_data)
  
  model_outputs <- get_model_outputs(lin_model)
  
  return(model_outputs)
}
```

```{r}
lm_pse_carb_network <- function(pse_var, carb_var){
  
  all_aqys <- unique(pse_carb_data$ID)
  
  lm_outputs <- run_lm_pse_carb_aqy(response = pse_var, predictor = carb_var)
  
  for(aqy in all_aqys){
    lm_aqy <- lm_pse_carb_aqy(aqy, pse_var, carb_var)
    
    lm_outputs <- rbind(lm_outputs, lm_aqy)
  }
  
  rownames(lm_outputs) <- NULL
  
  return(lm_outputs)
}
```

### Run Regressions
```{r}
pm_regression <- lm_pse_carb_network(pse_var = 'PM25_pse', carb_var = 'PM25_carb')
rh_regression <- lm_pse_carb_network(pse_var = 'RH_pse', carb_var = 'RH_carb')
temp_regression <- lm_pse_carb_network(pse_var = 'TEMP_pse', carb_var = 'TEMP_carb')
```

































