---
title: "Richmond Videos"
author: "Audrey Smith"
date: "11/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(stringr)

library(sp)
library(sf) 
library(leaflet) 
library(mapview)

library(raster)
library(gstat)
library(rgdal)

library(lubridate)

library(magick)

library(googledrive)
```

```{r}
read_and_calibrate_data <- function(start_time, end_time){
  
  print('Reading in raw AQY data')
  
  raw_data <- read.csv('PSE_AQY_10_min_2022-02-02.csv') %>% #update to local 
    filter(Time >= start_time & Time <= end_time)
  
  cal_params <- read.csv('pse_calvals_2022-02.csv') #update to local
  
  print('Calibrating AQY data')
  
  calibrated_data <- inner_join(raw_data, cal_params, by = 'ID') %>%
    filter(Time >= deployment_datetime & Time >= start_date & Time <= end_date) %>%
    rename('O3_raw'='O3', 'NO2_raw'='NO2', 'Ox_raw'='Ox') %>%
    mutate(O3 = O3.gain*(O3_raw-O3.offset), 
           Ox = Ox.gain*(Ox_raw-Ox.offset), NO2_int = O3 - NO2.a.value*Ox, NO2 = NO2.gain*(NO2_int-NO2.offset),
           PM25 = PM.gain*(PM25_raw - PM.offset)) %>%
    mutate_at(.vars = c('O3', 'Ox', 'NO2', 'PM25'), .funs = ~round(pmin(pmax(.x, 0), 500), 1)) %>%
    dplyr::select(ID, Time, Longitude, Latitude, O3_raw, O3, NO2_raw, NO2, PM25_raw, PM25, RH, TEMP, DP)
  
  return(calibrated_data)
  
}
```

```{r}
get_timestamps <- function(calibrated_data){
  
  time_column <- calibrated_data$Time
  
  unique_times <- unique(time_column)
  
  print(paste('Generating mapframes for', as.character(length(unique_times)), 'timestamps'))
  
  return(unique_times)
  
}
```

```{r}
get_simple_features <- function(calibrated_data){
  
  print('Generating simple features object for network')
  
  monitor_coordinates <- dplyr::select(calibrated_data, ID, Latitude, Longitude) %>%
    unique()
  
  monitor_sf <- st_as_sf(x = monitor_coordinates, coords = c('Longitude', 'Latitude'), crs = 4326, na.fail = F)
  
  return(monitor_sf)
}
```

```{r}
get_raster_coords <- function(monitor_sf){
  
  print('Generating raster coordinates from simple features object')
  
  monitor_raster <- raster(monitor_sf)
  
  x_min <- xmin(monitor_raster) - 0.08
  x_max <- xmax(monitor_raster) + 0.08
  y_min <- ymin(monitor_raster) - 0.025
  y_max <- ymax(monitor_raster) + 0.025
  
  center_x <- (x_min + x_max)/2
  center_y <- (y_min + y_max)/2
  
  raster_coords <- data.frame(cbind(x_min, x_max, y_min, y_max, center_x, center_y))
  
  return(raster_coords)
}
```

```{r}
get_raster_grid <- function(raster_coords){
  
  print('Generating raster grid from coordinates')
  
  raster_grid <- expand.grid(x = seq(from = raster_coords$x_min, to = raster_coords$x_max, by = 0.0008),
                             y = seq(from = raster_coords$y_min, to = raster_coords$y_max, by = 0.0008))
  
  coordinates(raster_grid) <- ~x+y
  gridded(raster_grid) <- TRUE
  
  return(raster_grid)
  
}
```

```{r}
get_color_palette <- function(pollutant_of_interest){
  
  upperbound <- switch(pollutant_of_interest, O3=100, NO2=50, PM25=50)
  
  color_palette <- colorNumeric(palette = c('navy', 'blue', 'cyan', 'yellow', 'red', 'red3'), 
                                domain = c(0, upperbound), na.color = 'darkred')
  
  return(color_palette)
}
```

```{r}
get_data_for_timestamp <- function(calibrated_data, timestamp, pollutant_of_interest){
  
  print(paste('Getting data for', pollutant_of_interest, 'at', timestamp))
  
  frame_data <- filter(calibrated_data, Time == timestamp) %>%
    dplyr::select(c('Time', pollutant_of_interest, 'Latitude', 'Longitude')) %>%
    rename('pollutant'=pollutant_of_interest) %>%
    na.omit()
  
  coordinates(frame_data) <- ~Longitude+Latitude
  
  return(frame_data)
  
}
```

```{r}
get_raster_for_timestamp <- function(timestamp_data, raster_grid){
  
  print('Interpolating data from last step')
  
  idw_interpolation <- idw(formula = as.formula('pollutant ~ 1'),  locations = timestamp_data, newdata = raster_grid)
  
  idw_raster <- raster(idw_interpolation)
  crs(idw_raster) <- crs('+proj=longlat +datum=WGS84 +no_defs')
  
  return(idw_raster)
  
}
```

```{r}
#get_wind_data <- function(start_time, end_time){
#  df_10m <- read.csv("wind_10m_avg.csv") %>% 
#  mutate(Date = mdy(Date)) %>% 
#  mutate(date_time = as.character(as.POSIXct(paste(Date, Time_10m), format="%Y-%m-%d %H:%M:%S"))) %>% 
#  dplyr::select(Station, date_time, Longitude, Latitude, windspd_10m_avg, winddir_10m_avg) %>% 
#  filter(date_time >= start_time & date_time <= end_time)

# Spatial transforms, converting from WGs84 to EPSG4326
#coords <- data.frame(lon = df_10m$Longitude, lat = df_10m$Latitude)
#coordinates(coords) <- c('lon', 'lat')
#proj4string(coords) <- CRS("+init=EPSG:4326")

# Converting EPSG4326 to EPSG3857 for analysis
#Metric_coords<-spTransform(coords,CRS("+init=EPSG:3857"))

#projected_coords <- data.frame(Metric_coords)


#start.x <- projected_coords$lon
#start.y <- projected_coords$lat

#w.speed <- df_10m$windspd_10m_avg
#w.direction <- df_10m$winddir_10m_avg
#w.date <- df_10m$date_time

#id <- c(1:length(start.x))

#df <- data.frame(id=id, start.x=start.x, start.y=start.y, w.speed=w.speed, w.direction=w.direction, w.date=w.date)
#head(df, 5)

#  return(df)
#}

#line.length <- 1000 #length of polylines representing wind in the map (meters)
#arrow.length <- 300 #lenght of arrowhead leg (meters)
#arrow.angle <- 120 #angle of arrowhead leg (degrees azimuth)

```


```{r}
#get_wind_arrow <- function(df, start_time, end_time, line.length, arrow.length, arrow.angle){
 # end.xy.df <- data.frame(end.x=NA,end.y=NA,end.arrow.x=NA,end.arrow.y=NA)

#  for (i in c(1:nrow(df))){

#coordinates of end points for wind lines (the initial points are the ones where data was observed)
 # if (isTRUE(df$w.direction[i] <= 90)) {
  #   end.x <- df$start.x[i] + (cos((90 - df$w.direction[i]) * 0.0174532925) * line.length)
  #} else if (isTRUE(df$w.direction[i] > 90 & df$w.direction[i] <= 180)) {
   #   end.x <- df$start.x[i] + (cos((df$w.direction[i] - 90) * 0.0174532925) * line.length)
  #} else if (isTRUE(df$w.direction[i] > 180 & df$w.direction[i] <= 270)) {
   #end.x <- df$start.x[i] - (cos((270 - df$w.direction[i]) * 0.0174532925) * line.length)
#  } else {end.x <- df$start.x[i] - (cos((df$w.direction[i] - 270) * 0.0174532925) * line.length)}

 # if (isTRUE(df$w.direction[i] <= 90)) {
  #    end.y <- df$start.y[i] + (sin((90 - df$w.direction[i]) * 0.0174532925) * line.length)
#  } else if (isTRUE(df$w.direction[i] > 90 & df$w.direction[i] <= 180)) {
 #     end.y <- df$start.y[i] - (sin((df$w.direction[i] - 90) * 0.0174532925) * line.length)
#  } else if (isTRUE(df$w.direction[i] > 180 & df$w.direction[i] <= 270)) {
  #    end.y <- df$start.y[i] - (sin((270 - df$w.direction[i]) * 0.0174532925) * line.length)
 # } else {end.y <- df$start.y[i] + (sin((df$w.direction[i] - 270) * 0.0174532925) * line.length)}

#coordinates of end points for arrowhead leg lines (the initial points are the previous end points)
#end.arrow.x <- end.x + (cos((df$w.direction[i] + arrow.angle) * 0.0174532925) * arrow.length)
#end.arrow.y <- end.y - (sin((df$w.direction[i] + arrow.angle) * 0.0174532925) * arrow.length)

#end.xy.df <- rbind(end.xy.df,c(end.x,end.y,end.arrow.x,end.arrow.y)) 
#}

#end.xy <- end.xy.df[-1,]
#df <- data.frame(df,end.xy)

#return(df)
#}

```

```{r}
#get_spatial_lines <- function(df, start_time, end_time){
 # lines <- data.frame(cbind(lng=c(df$start.x,df$end.x,df$end.arrow.x),
  #                        lat=c(df$start.y,df$end.y,df$end.arrow.y),
   #                       id=c(rep(df$id,3)))) %>% 
  #na.omit()

#lines.list <- list()


#for (i in c(1:max(lines$id))){
#line <- subset(lines,lines$id==i)
#line <- as.matrix(line[,c(1:2)])
#line <- Line(line) #object of class 'Line'
#lines.list[[i]] <- Lines(list(line), ID = i) #list of 'objects'Lines' 
#}

#sp.lines <- SpatialLines(lines.list) #object of class 'SpatialLines'
#proj4string(sp.lines) <- CRS("+init=EPSG:3857")

#sp.lines <- spTransform(sp.lines, CRS("+init=epsg:4326"))

#rownames(df) = df$id
#Join wind variables (id, speed, direction and date) to object of class 'SpatialLines'
#sp.lines.df <- SpatialLinesDataFrame(sp.lines, df[,c(1,4:6)]) #object of class 'SpatialLinesDataFrame'
#str(sp.lines.df)
#}

```



```{r}
get_map_for_timestamp <- function(timestamp_data, timestamp_raster, pollutant_of_interest, raster_coords, color_palette){
  
  print('Plotting it all on a map')
  
  upperbound <- switch(pollutant_of_interest, 'O3'=100, 50)
  units <- switch(pollutant_of_interest, 'PM25'='(ug/m3)', '(ppb)')
  time_mapped_date <- substr(unique(timestamp_data$Time), 1, 10)
  time_mapped_hour <- substr(unique(timestamp_data$Time), 12, 19)
  
  #pal_wind <- colorNumeric(palette = colorRampPalette(c("red", "blue"))(5),
                    #domain = 0:max(sp.lines.df@data$w.speed))
  
  timestamp_map <- leaflet(option = leafletOptions(zoomControl = F)) %>%
    addProviderTiles('Stamen.Terrain', group = 'Terrain') %>%
    setView(lat = raster_coords$center_y, lng = raster_coords$center_x, zoom = 13) %>%
    addRasterImage(timestamp_raster, colors = color_palette, opacity = 0.5, project = F) %>%
    addCircleMarkers(lng = timestamp_data$Longitude, lat = timestamp_data$Latitude, 
                     radius = 4, stroke = T, color = 'black', weight = 1, 
                     fill = T, fillColor = color_palette(timestamp_data$pollutant), fillOpacity = 1) %>%
    addLabelOnlyMarkers(lng = timestamp_data$Longitude, lat = timestamp_data$Latitude, 
                        label = timestamp_data$pollutant, labelOptions = labelOptions(noHide = TRUE, direction = 'bottom', textOnly = TRUE)) %>%
    #addPolylines(sp.lines.df, color = ~pal_wind(w.speed), opacity=1, weigh = 3, popup = labels) %>% 
    addLegend('bottomright', pal = color_palette, values = c(0, upperbound), 
              title = paste(pollutant_of_interest, units, '</br>', time_mapped_date, '</br>', time_mapped_hour), opacity = 1)
  
  path_for_map <- paste0('results_videos/', pollutant_of_interest, '_', time_mapped_date, '_', str_remove_all(time_mapped_hour, ':'), '.png')
  mapshot(x = timestamp_map, file = path_for_map)

}
```

```{r}
make_mapframe <- function(calibrated_data, timestamp, pollutant_of_interest, raster_grid, raster_coords, color_palette){
  
  timestamp_data <- get_data_for_timestamp(calibrated_data, timestamp, pollutant_of_interest)

  timestamp_raster <- get_raster_for_timestamp(timestamp_data, raster_grid)
  
  timestamp_map <- suppressWarnings(get_map_for_timestamp(timestamp_data, timestamp_raster, pollutant_of_interest, raster_coords, color_palette))
}
```

```{r}
animate_mapframe_timeseries <- function(pollutant_of_interest, start_time, end_time){
  
  mapframe_paths <- list.files('results_videos', '*.png', full.names = T)
  mapframe_paths <- sort(mapframe_paths)
  
  mapframe_images <- image_read(mapframe_paths)
  
  vid_start <- str_replace_all(str_remove_all(start_time, ':'), ' ', '-')
  vid_end <- str_replace_all(str_remove_all(end_time, ':'), ' ', '-')
  
  animation_path <- paste0('results_videos/', pollutant_of_interest, '_', vid_start, '_', vid_end, '.mp4')
  image_write_video(image = mapframe_images, path = animation_path, framerate = 4)
  
  print(paste('Wrote video to', animation_path))
  
}
```

````{r}
delete_existing_images <- function(){
  
  existing_images <- list.files('results_videos', '*.png')
  
  unlink(existing_images)
  
}
```

```{r}
make_pollution_video <- function(pollutant_of_interest, start_time, end_time){
  
  calibrated_data <- read_and_calibrate_data(start_time, end_time)
  
  #wind_data <- get_wind_data(start_time, end_time)
  
  monitor_sf <- get_simple_features(calibrated_data)
  
  
  raster_coords <- get_raster_coords(monitor_sf)
  raster_grid <- get_raster_grid(raster_coords)
  
  #wind_arrows <- get_wind_arrow(wind_data, start_time, end_time, line.length, arrow.length, arrow.angle)
  
  #sp.lines.df <- get_spatial_lines(wind_arrows, start_time, end_time)
  
  color_palette <- get_color_palette(pollutant_of_interest)
  
  timestamps <- get_timestamps(calibrated_data)
  
  delete_existing_images()
  
  lapply(timestamps, make_mapframe, calibrated_data=calibrated_data, pollutant_of_interest=pollutant_of_interest, raster_grid=raster_grid, raster_coords=raster_coords, color_palette=color_palette)
  
  animate_mapframe_timeseries(pollutant_of_interest, start_time, end_time)
}
```

```{r}
make_pollution_video('PM25', '2020-12-23 16:00:00', '2020-12-23 16:30:00')
```


















